/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 20:28:39,269 MSG: glogging.py:info:213 Worker exiting (pid: 1222)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:15:53,102 MSG: glogging.py:exception:219 Error handling request
Traceback (most recent call last):
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/dj_static.py", line 59, in __call__
    return self.application(environ, start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/base.py", line 51, in load_middleware
    mod = import_module(mw_module)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/middleware/view_log.py", line 7, in <module>
    from askbot.models import signals
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/models/__init__.py", line 2, in <module>
    startup_procedures.run()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/startup_procedures.py", line 1062, in run
    run_startup_tests()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/startup_procedures.py", line 1000, in run_startup_tests
    test_cache_backend()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/startup_procedures.py", line 835, in test_cache_backend
    cache.set('askbot-cache-test', test_value)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/cache.py", line 34, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/cache.py", line 88, in set
    return self.client.set(*args, **kwargs)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 121, in set
    client = self.client
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 56, in client
    _client = self.connect()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 103, in connect
    host, port, db = self.parse_connection_string(self._server)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 78, in parse_connection_string
    raise ImproperlyConfigured("Incorrect format '%s'" % (constring))
ImproperlyConfigured: Incorrect format 'soldierfish.redistogo.com:9551'
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:15:53,479 MSG: glogging.py:exception:219 Error handling request
Traceback (most recent call last):
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/dj_static.py", line 59, in __call__
    return self.application(environ, start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/base.py", line 51, in load_middleware
    mod = import_module(mw_module)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/middleware/view_log.py", line 7, in <module>
    from askbot.models import signals
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/models/__init__.py", line 2, in <module>
    startup_procedures.run()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/startup_procedures.py", line 1062, in run
    run_startup_tests()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/startup_procedures.py", line 1000, in run_startup_tests
    test_cache_backend()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/startup_procedures.py", line 835, in test_cache_backend
    cache.set('askbot-cache-test', test_value)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/cache.py", line 34, in _decorator
    return method(self, *args, **kwargs)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/cache.py", line 88, in set
    return self.client.set(*args, **kwargs)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 121, in set
    client = self.client
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 56, in client
    _client = self.connect()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 103, in connect
    host, port, db = self.parse_connection_string(self._server)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/redis_cache/client/default.py", line 78, in parse_connection_string
    raise ImproperlyConfigured("Incorrect format '%s'" % (constring))
ImproperlyConfigured: Incorrect format 'soldierfish.redistogo.com:9551'
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:16:01,840 MSG: glogging.py:info:213 Worker exiting (pid: 3505)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:16:49,662 MSG: glogging.py:info:213 Worker exiting (pid: 3552)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:16:57,620 MSG: glogging.py:info:213 Worker exiting (pid: 3553)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:17:04,730 MSG: glogging.py:info:213 Worker exiting (pid: 3554)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:17:24,795 MSG: glogging.py:exception:219 Error handling request
Traceback (most recent call last):
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/dj_static.py", line 59, in __call__
    return self.application(environ, start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/base.py", line 51, in load_middleware
    mod = import_module(mw_module)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/middleware/view_log.py", line 7, in <module>
    from askbot.models import signals
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/models/__init__.py", line 2, in <module>
    startup_procedures.run()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 222, in inner
    with self:
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 214, in __enter__
    self.entering(self.using)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 298, in entering
    enter_transaction_management(using=using)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 55, in enter_transaction_management
    connection.enter_transaction_management(managed)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:17:25,106 MSG: glogging.py:exception:219 Error handling request
Traceback (most recent call last):
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 131, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/dj_static.py", line 59, in __call__
    return self.application(environ, start_response)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 236, in __call__
    self.load_middleware()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/core/handlers/base.py", line 51, in load_middleware
    mod = import_module(mw_module)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/middleware/view_log.py", line 7, in <module>
    from askbot.models import signals
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/askbot/models/__init__.py", line 2, in <module>
    startup_procedures.run()
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 222, in inner
    with self:
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 214, in __enter__
    self.entering(self.using)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 298, in entering
    enter_transaction_management(using=using)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/transaction.py", line 55, in enter_transaction_management
    connection.enter_transaction_management(managed)
  File "/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/django/db/backends/dummy/base.py", line 15, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:17:27,401 MSG: glogging.py:info:213 Worker exiting (pid: 3583)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:17:49,450 MSG: glogging.py:info:213 Worker exiting (pid: 3620)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:19:23,108 MSG: glogging.py:info:213 Worker exiting (pid: 3621)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:19:28,556 MSG: glogging.py:info:213 Worker exiting (pid: 3646)
/Users/jasonamyers/.virtualenv/SacredPy/lib/python2.7/site-packages/gunicorn/glogging.py TIME: 2013-10-28 21:19:39,978 MSG: glogging.py:info:213 Worker exiting (pid: 3647)
